### ISSUE TITLE
Not getting proper response in case of ios

### ISSUE THREAD

**Issue by Dataingenious** [iNPUTmice/p2#11]
This is the stream i am sending from an ios device

<<"<iq xml:lang='en' to='chatserver.xgen.in' from='nipun.b@dil.in/13857236349007335285410' type='set' id='1234567890'>
<command xmlns='http://jabber.org/protocol/commands' action='execute' node='register-push-fcm'>
<x xmlns='jabber:x:data' type='submit'><field var='token'><value>656846848648468484864864684848646</value>
</field><field var='ios-id'><value>656846848648468484864864684848646</value></field></x></command></iq>">>

Following is the response i am getting

<<"<iq from=\"chatserver.xgen.in\" id=\"1234567890\" to=\"nipun.b@dil.in/13857236349007335285410\" type=\"error\" xml:lang=\"en\"><error type=\"modify\"><bad-request xmlns=\"urn:ietf:params:xml:ns:xmpp-stanzas\"></bad-request></error></iq>">>

**Comment by iNPUTmice** [comment]
The protocol between app and app server is proprietary. You can not just take any iOS app (you are not even mentioning which one) and expect it to work with p2.

**Comment by Dataingenious** [comment]
Chatsecure App source code
