### ISSUE TITLE
IQ Error responded on outgoing S2S connection

### ISSUE THREAD

**Issue by rufferson** [iNPUTmice/p2#12]
Hi,
When sending malformed IQ request the p2 server responds back directly in the same connection even though it didn't negotiate BIDI communication. Normal reply is properly routed via (separately opened) incoming  connection.
here's example:
```
31 > <iq type="set" id="XrLMFdT0FkLb"  to='p2.siacs.eu'  from='me@ruff.mobi/69bb954a2ce92de8b5'><command action='execute' xmlns='http://jabber.org/protocol/comm
ands' node='register-push-fcm'><x xmlns='jabber:x:data' type='submit'><field var='token'><value>...</value></field><field var='android-id'><value>...</value></field></x></command></iq>
New connection '32' from ::ffff:78.47.177.120
32 < <nsp0:iq id='XrLMFdT0FkLb' to='me@ruff.mobi/69bb954a2ce92de8b5' type='result' from='p2.siacs.eu' xmlns:nsp0='jabber:server'>...
```
This one is ok. Now malformed pubsub IQ:
```
34 > <iq id="9"  to='p2.siacs.eu' from='lest@ruff.mobi'><nsp0:pubsub xmlns:nsp0='http://jabber.org/protocol/pubsub'>
(note missing type='set')
34 < <nsp0:iq id='9' to='lest@ruff.mobi' type='error' from='p2.siacs.eu' xmlns:nsp0='jabber:server'>...
```
As result server rejects incoming stanza on unauthorised channel. While for malformed stanza it's not an issue (who cares) normal error processing will also be broken.

**Comment by iNPUTmice** [comment]
Three things:
* P2 is not a stand alone server. It needs a host like ejabberd or Prosody. P2 is not concerned with s2s connections
* I would assume that it ejabberd which rejects the malformed stanza. So if you believe this to be a bug you should open this with ejabberd
* Just because malformed stanzas are rejected that way (which might even make sense; i'm not that deep into s2s) doesn’t mean normal errors are handled the same.

**Comment by rufferson** [comment]
Ok, thanks for confirmation. I've tried to find what could handle s2s connection and didn't find it, rocks only doing component connection.
There's just this code
```
 public static IQHandler pubsubHandler = (iq -> {
        final PubSub pubSub = iq.getExtension(PubSub.class);
        if (pubSub != null && iq.getType() == IQ.Type.SET) {
        ... snip
        }
        return iq.createError(Condition.BAD_REQUEST);
    });
```
looks very much what I'm getting back which made me wonder if I'm missing anything.
