### ISSUE TITLE
Conversation 2.5.12

### ISSUE THREAD

**Issue by wkg** [iNPUTmice/p2#14]
Task 'assembleConversationsPlaystoreCompatDebug' not found in root project 'Conversations'.
Task 'assemblePlaystoreDebug' not found in root project 'Conversations'.
Task 'assemblePlaystoreSystemDebug' not found in root project 'Conversations'.
Task 'assemblePlaystoreCompatDebug' not found in root project 'Conversations'.

How now?

**Comment by wkg** [comment]
Sorry, forgot export sdk...

**Comment by niteshmoon** [comment]
@2561024 can you please tell me how you have solved this issue? I'm facing same and not able to resolve

**Comment by jeelshah22** [comment]
@2561024 Can you please tell me how you have solve this error, I'm facing same and not able to solve

**Comment by 143981** [comment]
> @2561024 Can you please tell me how you have solve this error, I'm facing same and not able to solve

export ANDROID_HOME=/media/hdd/media/Android/Sdk/
./gradlew assembleConversationsFreeDebug
