### ISSUE TITLE
FCM requirements and alternatives

### ISSUE THREAD

**Issue by scastillobib** [iNPUTmice/p2#15]
Hi!

After a quick read of the documentation, I have a doubt.
It seems to me than Firebase Cloud Messaging (FCM) is a required for p2 to work. And Google Play Services is required for FCM.
Am I wrong?

Is there any alternative to have Conversations push notifications under Lineage OS 16 (Android 9) without Google Play Services?

Thank you very much and regards.

**Comment by iNPUTmice** [comment]
> It seems to me than Firebase Cloud Messaging (FCM) is a required for p2 to work. And Google Play Services is required for FCM.

That is correct.

> Is there any alternative to have Conversations push notifications under Lineage OS 16 (Android 9) without Google Play Services?

When push is unavailable - either due to a lack of server support or due to missing operating system support Conversations will just maintain it's own connection to the XMPP server.
