### ISSUE TITLE
java[9720]: Failed to connect to 127.0.0.1:5347

### ISSUE THREAD

**Issue by anilk9096** [iNPUTmice/p2#17]
getting java[9720]: Failed to connect to 127.0.0.1:5347 

after successful build and enabled the service  with following config 

{
    "host": "127.0.0.1",
    "port": 5347,
    "jid": "xxxxxxxxxxxxxxx-im.com",
    "debug": false,
    "dbUrl": "jdbc:mariadb://localhost:3306/p2?characterEncoding=utf8",
    "dbUsername": "p2",
    "dbPassword": "XXXXXXXX",
    "fcm": {
        "authKey": "copyFromApiConsole"
    },
    "apns": {
        "certificate": "/etc/p2/apns_certificate.pem",
        "privateKey": "/etc/p2/apns_privatekey.pem",
        "bundleId": "com.example.xmpp",
        "sandbox": false
    }
}

root@ip-172-31-5-170:/etc/p2# systemctl status  p2.service 
p2.service - Conversations Push Proxy
   Loaded: loaded (/etc/systemd/system/p2.service; enabled)
   Active: active (running) since Mon 2020-01-27 15:02:56 UTC; 3min 30s ago
 Main PID: 9720 (java)
   CGroup: name=dsystemd:/system/p2.service
           └─9720 /usr/bin/java -jar /opt/p2-0.3.jar -c /etc/p2/config.json

Jan 27 15:05:38 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 27 15:05:43 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 27 15:05:48 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 27 15:05:53 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 27 15:05:58 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 27 15:06:03 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 27 15:06:08 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 27 15:06:13 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 27 15:06:18 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 27 15:06:23 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347

**Comment by iNPUTmice** [comment]
The readme has instructions on how to install and configure your XMPP Server.

**Comment by anilk9096** [comment]
hi , followed same and service enabled successfully . but getting error in app server 

p2.service - Conversations Push Proxy
   Loaded: loaded (/etc/systemd/system/p2.service; enabled)
   Active: active (running) since Mon 2020-01-27 15:02:56 UTC; 15h ago
 Main PID: 9720 (java)
   CGroup: name=dsystemd:/system/p2.service
           └─9720 /usr/bin/java -jar /opt/p2-0.3.jar -c /etc/p2/config.json

Jan 28 06:27:43 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 28 06:27:48 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 28 06:27:53 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 28 06:27:58 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 28 06:28:03 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 28 06:28:08 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 28 06:28:13 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 28 06:28:18 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 28 06:28:23 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 28 06:28:28 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
