### ISSUE TITLE
after build getting service status error

### ISSUE THREAD

**Issue by anilk9096** [iNPUTmice/p2#18]
p2.service - Conversations Push Proxy
   Loaded: loaded (/etc/systemd/system/p2.service; enabled)
   Active: active (running) since Mon 2020-01-27 15:02:56 UTC; 15h ago
 Main PID: 9720 (java)
   CGroup: name=dsystemd:/system/p2.service
           └─9720 /usr/bin/java -jar /opt/p2-0.3.jar -c /etc/p2/config.json

Jan 28 06:27:43 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 28 06:27:48 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 28 06:27:53 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 28 06:27:58 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 28 06:28:03 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 28 06:28:08 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 28 06:28:13 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 28 06:28:18 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 28 06:28:23 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347
Jan 28 06:28:28 ip-172-31-5-170 java[9720]: Failed to connect to 127.0.0.1:5347

**Comment by iNPUTmice** [comment]
* If you are a regular Conversations user you don’t need to run P2. You wouldn’t be able to use it anyway since our P2 server is hard coded in the app.
* If you are modifying Conversations to build your own app there are two possibilities:
    * You are doing this just for fun in which case I suggest you are using the free flavor and don’t worry about P2
    * You are doing this commercially in which case I’m available for consulting. For more information check out [my website](https://gultsch.de).
