### ISSUE TITLE
Unable to find SNAPSHOT dependency

### ISSUE THREAD

**Issue by guusdk** [iNPUTmice/p2#21]
Running `mvn package` on a clean (no `.m2` cache) computer results in the following error:

```
 Failed to execute goal on project p2: Could not resolve dependencies for project eu.siacs:p2:jar:0.3: Failure to find rocks.xmpp:xmpp-addr:jar:0.8.0-SNAPSHOT in https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced -> [Help 1]
```

Apache Maven version used: 3.3.9

As the `xmpp-addr-adapter` dependency defines a dependency to the same project, but version 0.8.0, I'd wager that using the 0.8.0-SNAPSHOT version is undesired/unexpected.

**Comment by iNPUTmice** [comment]
Fixed in 0576a8eba575f6791d35d1195b94ba6f4c4a88b0
