### ISSUE TITLE
APNS - Update Readme with instructions

### ISSUE THREAD

**Issue by licaon-kter** [iNPUTmice/p2#24]
....or at least mention that it supports the Apple system besides the Google one.

Yes, the code are the docs' but...

**Comment by nanitook** [comment]
Hi, can I get some help with this?
I'm trying to set up p2, but seems like I need some certificates from Apple for the apns. And also seems like I have to pay $100/yr to generate them.
Am I wrong?
Is there any way to set everything up without the apns?
