### ISSUE TITLE
P2 does not work properly

### ISSUE THREAD

**Issue by lovesuper** [iNPUTmice/p2#27]
After **success** handshaking with Ejabberd there is no more interaction except

> 2021-02-10 20:31:31.925680+03:00 [info] push17.com rejected notification for c7bd0ee3-84e8-4c27-85d5-15ab3ee996eb@im.local (eKxTS5n3bOe0) temporarily: Connection failed: connection refused (remote-server-timeout)

in ejabberd's log

**Comment by iNPUTmice** [comment]
> push17.com … connection refused

That’s all the information you need.

**Comment by lovesuper** [comment]
@iNPUTmice but push17.com is localhost alias in hosts file. You lib is actually not working. Debug mode is very wordless just a couple of log lines:

> Reading configuration from /home/lovesuper/Documents/p2/config.json
> OUT (null): <?xml version="1.0" encoding="UTF-8"?><stream:stream xmlns="jabber:component:accept" xmlns:stream="http://etherx.jabber.org/streams" to="push17.local" version="1.0" xml:lang="en-US">
> IN  (10863086799779518368): <?xml version="1.0" encoding="UTF-8" standalone="no"?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:component:accept" from="push17.local" id="10863086799779518368" xml:lang="en-US">
> OUT (10863086799779518368): <handshake>0069dba966aa5428f6c82d160a93d5a4f52750bb</handshake>
> IN  (10863086799779518368): <handshake></handshake>
> IN  (10863086799779518368): <iq from="push17.local" id="54e4bb0a-0492-464c-8ad2-c1a7c7fec6ac" to="push17.local" type="get"><ping xmlns="urn:xmpp:ping"></ping></iq>
> OUT (10863086799779518368): <iq from="push17.local" id="54e4bb0a-0492-464c-8ad2-c1a7c7fec6ac" to="push17.local" type="result"></iq>
> IN  (10863086799779518368): <iq from="push17.local" id="54e4bb0a-0492-464c-8ad2-c1a7c7fec6ac" to="push17.local" type="result"></iq>

Thats all. No connection errors from ejabberd. No any hints.

**Comment by iNPUTmice** [comment]
push17.com is not the same as push17.local

**Comment by lovesuper** [comment]
> push17.com is not the same as push17.local

Oh! My bad! Thanks. Just a lot of work for a day... :D
