### ISSUE TITLE
There is some actual issues with p2 java lib or deps

### ISSUE THREAD

**Issue by lovesuper** [iNPUTmice/p2#28]
When initiated a push from client app I faced with next error(s) in debugging console:

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.conscrypt.Platform (file:/home/lovesuper/.m2/repository/org/conscrypt/conscrypt-openjdk-uber/2.4.0/conscrypt-openjdk-uber-2.4.0.jar) to field java.net.Socket.impl
> WARNING: Please consider reporting this to the maintainers of org.conscrypt.Platform
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

And then:

> [IQ Handler Thread] WARN eu.siacs.p2.fcm.FcmPushService - push to FCM failed
> com.google.firebase.messaging.FirebaseMessagingException: Unknown error while making a remote service call: Error getting access token for service account: Socket is closed
> 	at com.google.firebase.messaging.FirebaseMessagingException.withMessagingErrorCode(FirebaseMessagingException.java:47)
> 	at com.google.firebase.messaging.FirebaseMessagingClientImpl$MessagingErrorHandler.createException(FirebaseMessagingClientImpl.java:293)
> 	at com.google.firebase.messaging.FirebaseMessagingClientImpl$MessagingErrorHandler.createException(FirebaseMessagingClientImpl.java:282)
> 	at com.google.firebase.internal.AbstractHttpErrorHandler.handleIOException(AbstractHttpErrorHandler.java:63)
> 	at com.google.firebase.internal.ErrorHandlingHttpClient.createHttpRequest(ErrorHandlingHttpClient.java:141)
> 	at com.google.firebase.internal.ErrorHandlingHttpClient.send(ErrorHandlingHttpClient.java:92)
> 	at com.google.firebase.internal.ErrorHandlingHttpClient.sendAndParse(ErrorHandlingHttpClient.java:72)
> 	at com.google.firebase.messaging.FirebaseMessagingClientImpl.sendSingleRequest(FirebaseMessagingClientImpl.java:127)
> 	at com.google.firebase.messaging.FirebaseMessagingClientImpl.send(FirebaseMessagingClientImpl.java:113)
> 	at com.google.firebase.messaging.FirebaseMessaging$1.execute(FirebaseMessaging.java:135)
> 	at com.google.firebase.messaging.FirebaseMessaging$1.execute(FirebaseMessaging.java:132)
> 	at com.google.firebase.internal.CallableOperation.call(CallableOperation.java:36)
> 	at com.google.firebase.messaging.FirebaseMessaging.send(FirebaseMessaging.java:102)
> 	at com.google.firebase.messaging.FirebaseMessaging.send(FirebaseMessaging.java:86)
> 	at eu.siacs.p2.fcm.FcmPushService.push(FcmPushService.java:67)
> 	at eu.siacs.p2.fcm.FcmPushService.push(FcmPushService.java:62)
> 	at eu.siacs.p2.controller.PushController.lambda$static$1(PushController.java:62)
> 	at rocks.xmpp.core.session.XmppSession.lambda$handleElement$14(XmppSession.java:1174)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
> 	at java.base/java.lang.Thread.run(Thread.java:832)
> Caused by: java.io.IOException: Error getting access token for service account: Socket is closed
> 	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:444)
> 	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:157)
> 	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:145)
> 	at com.google.auth.oauth2.ServiceAccountCredentials.getRequestMetadata(ServiceAccountCredentials.java:603)
> 	at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:91)
> 	at com.google.firebase.internal.FirebaseRequestInitializer.initialize(FirebaseRequestInitializer.java:55)
> 	at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:88)
> 	at com.google.firebase.internal.HttpRequestInfo.newHttpRequest(HttpRequestInfo.java:105)
> 	at com.google.firebase.internal.ErrorHandlingHttpClient.createHttpRequest(ErrorHandlingHttpClient.java:137)
> 	... 16 more
> Caused by: java.net.SocketException: Socket is closed
> 	at org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:404)
> 	at org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
> 	at org.conscrypt.ConscryptFileDescriptorSocket.waitForHandshake(ConscryptFileDescriptorSocket.java:483)
> 	at org.conscrypt.ConscryptFileDescriptorSocket.getOutputStream(ConscryptFileDescriptorSocket.java:470)
> 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:476)
> 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
> 	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
> 	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
> 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1194)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1082)
> 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1375)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1350)
> 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:220)
> 	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:113)
> 	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84)
> 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012)
> 	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:441)
> 	... 24 more
> OUT (15843014010067850753): <iq from="push17.local" id="rr-1612988430013-9910900519687832568-3gBhXXotihSf+Xw8vqu6RzaNGck=-55238004" to="im.just.ooo" type="error"><error type="wait"><recipient-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"></recipient-unavailable></error></iq>
> 

I don't get why does this happen? Firebase .json file is in direct script's access and with debugging I assured the config object is right configured and all is stuck at http request.

Appreciate your help.

**Comment by lovesuper** [comment]
Some ideas?

**Comment by Kashcheyeu** [comment]
Are you using JDK 15? The _ideal_ way to resolve this would be to

> **reporting this to the maintainers of org.conscrypt.Platform**

and asking them to fix such reflective access going forward.

From one of the [threads on the mailing list](https://mail.openjdk.java.net/pipermail/jigsaw-dev/2017-May/012673.html):

> If the default mode permits illegal reflective access, however, then it's essential to make that known so that people aren't surprised when this is no longer the default mode in a future release.

**Comment by dongnguyen7** [comment]
@lovesuper Have you resolved this issue yet?
