### ISSUE TITLE
Task 'assemblePlaystoreDebug' not found

### ISSUE THREAD

**Issue by streaps** [iNPUTmice/p2#4]
Documentation issue in README.md #Building Conversations

```
./gradlew assemblePlaystoreDebug
[...]
Task 'assemblePlaystoreDebug' not found in root project 'Conversations'.
```
should I use
`./gradlew assemblePlaystoreSystemDebug`
or
`./gradlew assemblePlaystoreCompatDebug`
?

(I'm just a user, not an Android developer)

**Comment by iNPUTmice** [comment]
* wrong repository
* the `README.me` has instructions on how to build Conversations
