### ISSUE TITLE
[help] P2 integration with prosody

### ISSUE THREAD

**Issue by ymahlaoui** [iNPUTmice/p2#6]
https://github.com/iNPUTmice/p2#xmpp-server

Is there a way to configure the prosody cloud_notify module [https://modules.prosody.im/mod_cloud_notify.html#fnref1](url) ?

Thanks

**Comment by iNPUTmice** [comment]
The documentation on how to configure on external component in Prosody can be found here: https://prosody.im/doc/components

**Comment by ymahlaoui** [comment]
Thank's @iNPUTmice
